Ejercicio Uno POO
juanfelipemh/POO_Ejercicios pull request #2
Opened 2023-01-19 19:05 UTC by juanfelipemh

Ejercicio uno resuelto, implementando sus clases y modelo, además, instanciado para que se pueda ejecutar en el Main.

Main debe:

- Instanciar pedro
- Crear el modelo persona de pedro
- en pedro Llamar llenar informacion y enviar el modelo de pedro
- en pedro Llamar tocar piano
- en pedro llamar caminar
- Crear un mensaje con la informacion de pedro, que se almaceno en la variable global del padre que diga “Pedro tiene pelo de color{ColorPelo} de nombre {Nombre } y Edad {edad}
- Instanciar pepita
- Crear modelo persona de pepita
- En pepita llamar llenar informacion y enviar el modelo de pepita
- En pepita llamar caminar
- En pepita llamar tocar flauta e imprimir el mensaje en consola

2023-01-20 17:25 UTC, MauroCaro commented on EjercicioUno/build.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This field is a build

Remember a build is executed on your local machine every time you compile, for that reason, this can't be included in the remote.

In order to exclude this file please add a Git ignore and ignore this file

2023-01-20 17:26 UTC, MauroCaro commented on EjercicioUno/nbproject/genfiles.properties
> +build.xml.data.CRC32=d79b96f5
This file is a build generated file

Remember a build is executed on your local machine every time you compile, for that reason, this can't be included in the remote.

In order to exclude this file please add a Git ignore and ignore this file

Here is an example of your git ignore

https://github.com/github/gitignore/blob/main/Global/NetBeans.gitignore

2023-01-20 17:27 UTC, MauroCaro commented on EjercicioUno/nbproject/private/private.properties
> +compile.on.save=true
This file is a build generated file

Remember a build is executed on your local machine every time you compile, for that reason, this can't be included in the remote.

In order to exclude this file please add a Git ignore and ignore this file

Here is an example of your git ignore

https://github.com/github/gitignore/blob/main/Global/NetBeans.gitignore

2023-01-20 17:27 UTC, MauroCaro commented on EjercicioUno/nbproject/private/private.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file is a build generated file

Remember a build is executed on your local machine every time you compile, for that reason, this can't be included in the remote.

In order to exclude this file please add a Git ignore and ignore this file

Here is an example of your git ignore

https://github.com/github/gitignore/blob/main/Global/NetBeans.gitignore

2023-01-20 17:27 UTC, MauroCaro commented on EjercicioUno/nbproject/project.properties
> +annotation.processing.enabled=true
This file is a build generated file

Remember a build is executed on your local machine every time you compile, for that reason, this can't be included in the remote.

In order to exclude this file please add a Git ignore and ignore this file

Here is an example of your git ignore

https://github.com/github/gitignore/blob/main/Global/NetBeans.gitignore

2023-01-20 17:29 UTC, MauroCaro commented on EjercicioUno/src/Clases/Persona.java
> +        public String imprimirInformaciónPersona() {
Never include accents in code unless is a string for the user, so call this method

`imprimirInformacionPersona`

2023-01-20 17:30 UTC, MauroCaro commented on EjercicioUno/src/Clases/Persona.java
> +        public ModeloPersona crearPersona;
Better naming for this variable can be

`personaGlobal`

Since "crearPersona" give the sensation to the developer that calling this variable would create the person object and that is not the purpose of having it

2023-01-20 17:33 UTC, MauroCaro commented on EjercicioUno/src/Clases/Pedro.java
> +        return "Pedro esta caminando muy rapido..."; // Se le asigna el nuevo atributo a caminar
The message " Se le asigna el nuevo atributo a caminar " is not correct

You are not assigning another attribute, you are **overriding the behavior**

Please fix it

2023-01-20 17:33 UTC, MauroCaro commented on EjercicioUno/src/Clases/Pepita.java
> +        return super.caminar(); // Llama el método creado en la clase Padre
Nice 👏

2023-01-20 17:35 UTC, MauroCaro commented on README.md
> +  <li>En edro llamar llenar informacion y enviar el modelo de Pedro</li>
You are missing a `P`

2023-01-20 17:35 UTC, MauroCaro commented on README.md
> +<img src="https://compilandoconocimiento.files.wordpress.com/2017/01/miniatura-2.png" alt="Imagen Java" width="250"/>
It would be good if you included an English version read.me as well

2023-01-20 17:58 UTC, MauroCaro commented on EjercicioUno/src/ejerciciouno/EjercicioUno.java
> +            System.out.println("Pepita tiene el pelo de color " + pedro.crearPersona.getColorPelo() + " de nombre " + pedro.crearPersona.getNombre() + " y su edad es " + pedro.crearPersona.getEdad())
Please check pedro is not correct

2023-01-20 18:24 UTC, MauroCaro requested changes
Please check the comments

2023-01-20 18:25 UTC, MauroCaro commented
This is a suggestion you can also read this documentation in order to see how to document your code in a very good way and apply it to this project


https://www.baeldung.com/javadoc
http://www.drjava.org/docs/user/ch10.html

2023-01-22 13:41 UTC, juanfelipemh commented on EjercicioUno/build.xml
> +<?xml version="1.0" encoding="UTF-8"?>
git ignore was updated

2023-01-22 13:41 UTC, juanfelipemh commented on EjercicioUno/nbproject/genfiles.properties
> +build.xml.data.CRC32=d79b96f5
git ignore was updated

2023-01-22 13:41 UTC, juanfelipemh commented on EjercicioUno/nbproject/private/private.properties
> +compile.on.save=true
git ignore was updated

2023-01-22 13:41 UTC, juanfelipemh commented on EjercicioUno/nbproject/project.properties
> +annotation.processing.enabled=true
git ignore was updated

2023-01-23 16:53 UTC, MauroCaro requested changes
You add the git ignore but left the files included, please take out the files that should not be included

2023-01-23 16:54 UTC, MauroCaro commented on EjercicioUno/src/ejerciciouno/EjercicioUno.java
> +            Pedro pedro1 = new Pedro();
Please avoid at all cost having variable such as 

"Pedro1", "Pedro2", etc

So this variable can be named "Pedro"

2023-01-23 16:55 UTC, MauroCaro commented on EjercicioUno/src/ejerciciouno/EjercicioUno.java
> +            Pepita pepita1 = new Pepita();
Please avoid at all cost having variable such as

"Pepita1", "Pepita2", etc

So this variable can be named "Pepita"

2023-01-23 16:55 UTC, MauroCaro reviewed
Please chekc omments

2023-01-25 17:21 UTC, MauroCaro approved these changes

2023-01-25 17:22 UTC, MauroCaro commented
PR approved and can be merged!

2023-01-25 17:33 UTC, merged