Exercise # 2 - POO
juanfelipemh/POO_Ejercicios pull request #3
Opened 2023-01-26 15:22 UTC by juanfelipemh

The project contains the following:

- Project have their respectives objects and interfaces
- you can build and run the main "EjercicioDos" to get the results

2023-01-30 17:27 UTC, MauroCaro commented on EjercicioDos/src/clases/ModeloAnimal.java
> +
Please delete empty space

2023-01-30 17:28 UTC, MauroCaro commented on EjercicioDos/src/clases/Ave.java
> +
Please delete empty space

2023-01-30 17:28 UTC, MauroCaro commented on EjercicioDos/src/clases/Ave.java
> +         if(tieneNido){
Nice 👏

2023-01-30 17:30 UTC, MauroCaro commented on EjercicioDos/src/clases/Mamifero.java
> +    public String agruparManda(int cantidad){
Just I'm wondering what about if cantidad is just 1

The message would be then "La manada se agrupa y en total hay 1 animales"

So the message is not totally correct, what about if you add validation to improve the message for 0 and 1 and do not allow negative numbers

2023-01-30 18:02 UTC, MauroCaro commented on EjercicioDos/src/clases/Colibri.java
> +
Delete empty space

2023-01-31 01:29 UTC, MauroCaro commented on EjercicioDos/src/clases/Ave.java
> +         if(tieneNido){
I want to teach another way you can have this in just one line

Is called ternary operator
https://www.baeldung.com/java-ternary-operator

So you can have your code to look like this

  `  return tieneNido == true ? "Tiene nido" : "No tiene nido";`

2023-01-31 01:30 UTC, MauroCaro commented on EjercicioDos/src/clases/Vaca.java
> +        if(valor % 2 == 0){
What about if you use ternary operator here?

2023-01-31 01:32 UTC, MauroCaro commented on EjercicioDos/src/ejerciciodos/EjercicioDos.java
> +        System.out.println(vaca.reencarnar("Vamos lola "));
There is an error on the printing message

Vamos lola  �Tu puedes hacerlo!

Please check

2023-01-31 01:33 UTC, MauroCaro commented on EjercicioDos/src/clases/Colibri.java
> +        public Colibri(ModeloAnimal datosColibri){
Please indent code

2023-01-31 01:35 UTC, MauroCaro requested changes
Awesome Job 👏 Just check the comments

2023-01-31 12:09 UTC, juanfelipemh commented on EjercicioDos/src/clases/ModeloAnimal.java
> +
Solved!

2023-01-31 12:15 UTC, juanfelipemh commented on EjercicioDos/src/clases/Ave.java
> +         if(tieneNido){
Thank Mauro. I knew about ternary operator but this is my first time using in Java.
Done!

2023-01-31 12:24 UTC, juanfelipemh commented on EjercicioDos/src/clases/Mamifero.java
> +    public String agruparManda(int cantidad){
Done! Code was updated with validations

2023-01-31 12:25 UTC, juanfelipemh commented on EjercicioDos/src/clases/Colibri.java
> +
Done!

2023-01-31 12:26 UTC, juanfelipemh commented on EjercicioDos/src/clases/Vaca.java
> +        if(valor % 2 == 0){
Just I updated to ternary operator 
Done!

2023-01-31 12:27 UTC, juanfelipemh commented on EjercicioDos/src/ejerciciodos/EjercicioDos.java
> +        System.out.println(vaca.reencarnar("Vamos lola "));
Updated!

2023-02-02 02:40 UTC, MauroCaro commented on EjercicioDos/src/clases/Vaca.java
> +        System.out.println(valor % 2 == 0 ? "La fecha de su muerte " + anoFallecimiento + ", el numero es par y vivio " +  edad + " anios y murio por " + causaMuerte : "La fecha de su muerte " + anoF
You can still improving this code, instead of repeting the message you can use the ternary operator exactly were you need it

`
 System.out.println("La fecha de su masuerte " + anoFallecimiento + ", el numero es " + (valor % 2 == 0 ? "par" :"impar")+ " y vivio " + edad + " anios y murio por " + causaMuerte);`

2023-02-02 02:43 UTC, MauroCaro commented on EjercicioDos/src/clases/Colibri.java
> +    public void morir(int anoNacimiento, int anoFallecimiento, String causaMuerte) {
I don't understand why did you change this to void.

muerte must return a String so you have to return the message as you have it before

2023-02-02 02:43 UTC, MauroCaro commented on EjercicioDos/src/clases/Vaca.java
> +    public void morir(int anoNacimiento, int anoFallecimiento, String causaMuerte) {
I don't understand why did you change this to void.

muerte must return a String so you have to return the message as you have it before

2023-02-02 02:44 UTC, MauroCaro requested changes
Please check comments

2023-02-02 13:09 UTC, juanfelipemh commented on EjercicioDos/src/clases/Vaca.java
> +        System.out.println(valor % 2 == 0 ? "La fecha de su muerte " + anoFallecimiento + ", el numero es par y vivio " +  edad + " anios y murio por " + causaMuerte : "La fecha de su muerte " + anoF
Mauro, code was refactored

2023-02-02 13:10 UTC, juanfelipemh commented on EjercicioDos/src/clases/Colibri.java
> +    public void morir(int anoNacimiento, int anoFallecimiento, String causaMuerte) {
Corrected!

2023-02-02 13:10 UTC, juanfelipemh commented on EjercicioDos/src/clases/Vaca.java
> +    public void morir(int anoNacimiento, int anoFallecimiento, String causaMuerte) {
Corrected!

2023-02-03 18:10 UTC, MauroCaro approved these changes
PR approved and can be merged

2023-02-03 18:11 UTC, merged