Develop
juanfelipemh/POO_Ejercicios pull request #4
Opened 2023-02-08 16:43 UTC by juanfelipemh

Find the code of the calculator. This PR include completed app

2023-02-09 14:43 UTC, MauroCaro commented on EjercicioTres/README.md
> +  <li>Run the project and I must be have a menu with options: 1.basic, 2.advanced and 3.child calculator, Also, 4.result option and 5.exit of the calculator</li>
correct:

`Run the project and it must have a menu with options: 1. basic, 2. advanced and 3. child calculator, Also, 4. Result history option and 5. exit of the calculator`

2023-02-09 14:45 UTC, MauroCaro commented on EjercicioTres/README.md
> +  <li>If I select option 2, must be show and option menu with: Addition, subtraction, multiplication, division, pow and square root. Also, an option to return to main menu</li>
Please correct

`If I select option 2, must show an options menu with Addition, subtraction, multiplication, division, pow and square root. Also, an option to return to the main menu`

2023-02-09 14:47 UTC, MauroCaro commented on EjercicioTres/README.md
> +  <li>If I select option 3, must be show and option menu with: Addition, subtraction, multiplication and division. Also, an option to return to main menu</li>
Please correct

`If I select option 3, must be shown an options menu with Addition, subtraction, multiplication and division. Also, an option to return to the main menu`

2023-02-09 14:47 UTC, MauroCaro commented on EjercicioTres/README.md
> +  <li>Each operation must be show the result</li>
Please correct

`Each operation must show the result`

2023-02-09 14:49 UTC, MauroCaro commented on EjercicioTres/src/clases/Calculadora.java
> +    public String dato;
Please add a more meaningful name, dato of what?

2023-02-09 14:51 UTC, MauroCaro commented on EjercicioTres/src/clases/Calculadora.java
> +        this.historial = new ArrayList<>();
You can initialize the variable once you create it on line 11 by doing

`    public List<String> historial = new ArrayList<>();`

And then delete the constructor method since you won't need it

2023-02-09 14:52 UTC, MauroCaro commented on EjercicioTres/src/clases/Calculadora.java
> +        String datos;
Please add a more meaningful name, datos of what?

2023-02-09 14:58 UTC, MauroCaro commented on EjercicioTres/src/clases/Calculadora.java
> +        String patronSplit = "\\+|-|\\*|/";
This is a really good candidate to have as a constant

so you can create a global variable for example

`final String PATRON_SPLIT_CALCULAR = "\\+|-|\\*|/";`


https://lineadecodigo.com/java/constantes-en-java/

2023-02-09 15:21 UTC, MauroCaro commented on EjercicioTres/src/clases/Calculadora.java
> +        for (int i = 1; i < numeros.size(); i++) {
I am not completely sure of this, but I think you can improve this code by doing

for ( double i : Iterables.skip(numeros, 1) ) {     
    // 1st element will be skipped
}

Please check otherwise you can leave it like this

2023-02-09 15:22 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +        return super.calcular();
If you are just calling the parent you don't need to override this method

2023-02-09 15:22 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +        return super.suma(numeros);
If you are just calling the parent you don't need to override this method

2023-02-09 15:23 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +        return super.resta(numeros);
If you are just calling the parent you don't need to override this method

2023-02-09 15:23 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +        return super.division(numeros);
If you are just calling the parent you don't need to override this method

2023-02-09 15:23 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +            num = Math.pow(numero, 2);
😍 Awesome!

2023-02-09 15:24 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +            num = Math.sqrt(numero);
😍 😍 Awesomeee

2023-02-09 18:11 UTC, juanfelipemh commented on EjercicioTres/README.md
> +  <li>Run the project and I must be have a menu with options: 1.basic, 2.advanced and 3.child calculator, Also, 4.result option and 5.exit of the calculator</li>
Updated!

2023-02-09 18:12 UTC, juanfelipemh commented on EjercicioTres/README.md
> +  <li>If I select option 2, must be show and option menu with: Addition, subtraction, multiplication, division, pow and square root. Also, an option to return to main menu</li>
Updated!

2023-02-09 18:12 UTC, juanfelipemh commented on EjercicioTres/README.md
> +  <li>If I select option 3, must be show and option menu with: Addition, subtraction, multiplication and division. Also, an option to return to main menu</li>
Updated!

2023-02-09 18:12 UTC, juanfelipemh commented on EjercicioTres/README.md
> +  <li>Each operation must be show the result</li>
Updated!

2023-02-09 18:16 UTC, juanfelipemh commented on EjercicioTres/src/clases/Calculadora.java
> +    public String dato;
Renamed variable

2023-02-09 18:19 UTC, juanfelipemh commented on EjercicioTres/src/clases/Calculadora.java
> +        this.historial = new ArrayList<>();
Constructor deleted and variable was initialized on line 11

2023-02-09 18:19 UTC, juanfelipemh commented on EjercicioTres/src/clases/Calculadora.java
> +        String datos;
Renamed variable

2023-02-09 18:24 UTC, juanfelipemh commented on EjercicioTres/src/clases/Calculadora.java
> +        String patronSplit = "\\+|-|\\*|/";
Thanks Mauricio for this information. This line was updated as a constant

2023-02-09 18:39 UTC, juanfelipemh commented on EjercicioTres/src/clases/Calculadora.java
> +        for (int i = 1; i < numeros.size(); i++) {
Mauro,
I'm checking this code and it was compared with a manual calculator. The operation result in both was the same. I had exploring some solutions and this was the best result.

2023-02-09 18:48 UTC, juanfelipemh commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +        return super.suma(numeros);
Override deleted

2023-02-09 18:48 UTC, juanfelipemh commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +        return super.resta(numeros);
Override deleted

2023-02-09 18:48 UTC, juanfelipemh commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +        return super.multiplicacion(numeros);
Override deleted

2023-02-09 18:48 UTC, juanfelipemh commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +        return super.division(numeros);
Override deleted

2023-02-09 18:50 UTC, juanfelipemh commented on EjercicioTres/README.md
> +  <li>If I select option 1, must be show and option menu with: Addition, subtraction, multiplication and division. Also, an option to return to main menu</li>
Updated!

2023-02-10 17:31 UTC, MauroCaro requested changes
Just minor comments

2023-02-10 17:31 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +                    double total;
All these variables total are actually not needed to be saved on memory since you are only using it for the message so you can use it directly, Apply this to the rest of the code

`  JOptionPane.showMessageDialog(null, "El resultado de la suma " + datoOperacion + " es: " + suma(numerosSuma));
`

2023-02-10 17:31 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraBasica.java
> +                case 5 -> {
You don't need to add case 5, since you are not doing anything

2023-02-10 17:31 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +                case 7 -> {
You don't need to add case 7 since you are not doing anything

2023-02-10 17:31 UTC, MauroCaro commented on EjercicioTres/src/clases/CalculadoraInfantil.java
> +                case 5 -> {
You don't need to add case 5 since you are not doing anything

2023-02-10 18:45 UTC, juanfelipemh commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +                    double total;
Correct Mauro. I update the message code and delete this variable

2023-02-10 18:56 UTC, juanfelipemh commented on EjercicioTres/src/clases/CalculadoraBasica.java
> +                case 5 -> {
I have default validation. If number is not in the cases, the app shown a error. 
if I delete the case, the program show the error and after this exit to the main menu. With the case, this show the main menu

2023-02-10 18:56 UTC, juanfelipemh commented on EjercicioTres/src/clases/CalculadoraAvanzada.java
> +                case 7 -> {
I have default validation. If number is not in the cases, the app shown a error. 
if I delete the case, the program show the error and after this exit to the main menu. With the case, this show the main menu

2023-02-10 18:56 UTC, juanfelipemh commented on EjercicioTres/src/clases/CalculadoraInfantil.java
> +                case 5 -> {
I have default validation. If number is not in the cases, the app shown a error. 
if I delete the case, the program show the error and after this exit to the main menu. With the case, this show the main menu

2023-02-13 02:20 UTC, MauroCaro approved these changes
Good work, PR can be merged now

2023-02-13 02:31 UTC, merged